title: Unfufadoo's Testing Site
author: Sean Lewis
email: unfufadoo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Unfufadoo's Code Emporium, for all your coding needs! Only 299.00/mo!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
